name: "Build Zebra & Zaino"
inputs:
  MINER_SEED:
    required: true
  MINER_ADDRESS:
    required: true
  SEED:
    required: true
  DESTINATION_ADDRESS:
    required: true
runs:
  using: "composite"
  steps:
    - name: Cache zebra
      id: cache-zebra
      uses: actions/cache@v5
      with:
        path: |
          ./tools/bin
        key: ${{ runner.os }}-zebra-lwd-5.0.0

    - name: Install zebra & zaino
      if: steps.cache-zebra.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo apt update && sudo apt install -y libclang-dev clang

        cargo install --git https://github.com/ZcashFoundation/zebra --tag v5.0.0 --features=internal-miner --root ./tools zebrad
        go install github.com/zcash-shielded-assets/lightwalletd@44adcde
        cp $HOME/go/bin/lightwalletd tools/bin

    - name: Install zkool
      if: steps.cache-zebra.outputs.cache-hit != 'true'
      shell: bash
      run: cargo install --git https://github.com/hhanh00/zkool2 --tag zkool-v6.17.0 --features=graphql --root ./tools --bin zkool_graphql
      env:
        RUSTFLAGS: '--cfg zcash_unstable="nu7"'

    - name: Save cache
      if: steps.cache-zebra.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        path: ./tools/bin
        key: ${{ runner.os }}-zebra-lwd-5.0.0

    - name: Install config
      if: github.repository != 'hhanh00/zkool2'
      shell: bash
      run: |
        curl -sf --create-dirs https://raw.githubusercontent.com/hhanh00/zkool2/refs/heads/main/misc/zebra.toml -o misc/zebra.toml
        curl -sf --create-dirs https://raw.githubusercontent.com/hhanh00/zkool2/refs/heads/main/misc/zcash.conf -o misc/zcash.conf
        curl -sf --create-dirs https://raw.githubusercontent.com/hhanh00/zkool2/refs/heads/main/example/sh/mine.sh -o example/sh/mine.sh
        chmod +x ./example/sh/mine.sh

    - name: Add tools to PATH
      shell: bash
      run: echo "$GITHUB_WORKSPACE/tools/bin" >> $GITHUB_PATH

    - name: Start regtest, mine and shield to wallet
      shell: bash
      run: ./example/sh/mine.sh
      env:
        MINER_SEED: ${{ inputs.MINER_SEED }}
        MINER_ADDRESS: ${{ inputs.MINER_ADDRESS }}
        SEED: ${{ inputs.SEED }}
        DESTINATION_ADDRESS: ${{ inputs.DESTINATION_ADDRESS }}
