// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'network.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<void> initDatadir({required String directory}) =>
    RustLib.instance.api.crateApiNetworkInitDatadir(directory: directory);

Future<int> getCurrentHeight({required Coin c}) =>
    RustLib.instance.api.crateApiNetworkGetCurrentHeight(c: c);

Future<double> getCoingeckoPrice(
        {required String api, required String currency}) =>
    RustLib.instance.api
        .crateApiNetworkGetCoingeckoPrice(api: api, currency: currency);

Future<String> getNetworkName({required Coin c}) =>
    RustLib.instance.api.crateApiNetworkGetNetworkName(c: c);

Future<List<LWDInfo>> queryLwdList() =>
    RustLib.instance.api.crateApiNetworkQueryLwdList();

@freezed
sealed class LWDInfo with _$LWDInfo {
  const factory LWDInfo({
    required String url,
    required bool isTor,
    required int height,
    required String status,
    required int uptime,
    required String version,
    required int ping,
  }) = _LWDInfo;
}
