// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> initDatadir({required String directory}) =>
    RustLib.instance.api.crateApiNetworkInitDatadir(directory: directory);

Future<int> getCurrentHeight({required Coin c}) =>
    RustLib.instance.api.crateApiNetworkGetCurrentHeight(c: c);

Future<double> getCoingeckoPrice(
        {required String api, required String currency}) =>
    RustLib.instance.api
        .crateApiNetworkGetCoingeckoPrice(api: api, currency: currency);

Future<String> getNetworkName({required Coin c}) =>
    RustLib.instance.api.crateApiNetworkGetNetworkName(c: c);
