// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../io.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Stream<SyncProgress> synchronize(
        {required List<int> accounts,
        required int currentHeight,
        required int actionsPerSync,
        required int transparentLimit,
        required int checkpointAge,
        required int blockChunkSize,
        required bool fast,
        required Coin c}) =>
    RustLib.instance.api.crateApiSyncSynchronize(
        accounts: accounts,
        currentHeight: currentHeight,
        actionsPerSync: actionsPerSync,
        transparentLimit: transparentLimit,
        checkpointAge: checkpointAge,
        blockChunkSize: blockChunkSize,
        fast: fast,
        c: c);

Future<PoolBalance> balance({required Coin c}) =>
    RustLib.instance.api.crateApiSyncBalance(c: c);

Future<void> cancelSync() => RustLib.instance.api.crateApiSyncCancelSync();

Future<void> rewindSync(
        {required int height, required int account, required Coin c}) =>
    RustLib.instance.api
        .crateApiSyncRewindSync(height: height, account: account, c: c);

Future<SyncHeight> getDbHeight({required Coin c}) =>
    RustLib.instance.api.crateApiSyncGetDbHeight(c: c);

Future<void> fetchTxDetails({required int account, required Coin c}) =>
    RustLib.instance.api.crateApiSyncFetchTxDetails(account: account, c: c);

Future<void> cacheBlockTime({required int height, required Coin c}) =>
    RustLib.instance.api.crateApiSyncCacheBlockTime(height: height, c: c);

class PoolBalance {
  final Uint64List field0;

  const PoolBalance({
    required this.field0,
  });

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PoolBalance &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

class SyncProgress {
  final int height;
  final int time;

  const SyncProgress({
    required this.height,
    required this.time,
  });

  @override
  int get hashCode => height.hashCode ^ time.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncProgress &&
          runtimeType == other.runtimeType &&
          height == other.height &&
          time == other.time;
}
