name: Build and Release GraphQL Server

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
  push:
    tags:
      - zkool-v*

jobs:
  build:
    if: ${{ !startsWith(github.head_ref, 'release-please--branches--') }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Install RUST
        uses: dtolnay/rust-toolchain@stable
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Build zkool_graphql
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libudev-dev
          cd rust
          cargo build --release --bin zkool_graphql --features=graphql
        env:
          RUSTFLAGS: '--cfg zcash_unstable="nu7"'
      - name: Create Release
        if: startsWith(github.ref_name, 'zkool-v')
        uses: softprops/action-gh-release@v3
        with:
          files: ./target/release/zkool_graphql
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
