name: Wallet Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    if: ${{ !startsWith(github.head_ref, 'release-please--branches--') }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Install RUST
        uses: dtolnay/rust-toolchain@stable
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup regtest
        uses: hhanh00/zkool2/.github/actions/zebra@main
        with:
          MINER_SEED: "burger voice warrior danger satoshi you solid atom elite alcohol category layer able debate culture talk tissue language hip surge fiction paddle stove voyage"
          MINER_ADDRESS: "tmQ1BiNRfsvT6eMkJ5n7nMZsbz1PGwCs1Zs"
          SEED: "invite couch cloud pave stuff cabbage usual rigid dragon warm cable price fame warfare next swallow worth opera suggest flame patch undo position arctic"
          DESTINATION_ADDRESS: uregtest1ur83jamvhc5pwe8xzlu9d8ur4mxmny385mhlurxh5z00e6vhcf9zk0dncar334n0ucskdya9ytdrvzucprqjrhy7hd6rkklp0q6eyxp5
      - name: Build zkool_graphql
        run: |
            sudo apt-get update
            sudo apt-get install -y pkg-config libudev-dev
            cd rust
            cargo build --release --bin zkool_graphql --features=graphql
        env:
          RUSTFLAGS: '--cfg zcash_unstable="nu7"'
      - name: Run pytest tests
        run: |
          cd tests
          pip install uv
          uv sync --all-groups
          uv run pytest tests/test_smoke.py tests/test_subscriptions.py tests/test_dkg.py tests/test_frost.py tests/test_jwt.py tests/test_transactions.py tests/test_account_management.py tests/test_tx_details.py tests/test_reorg.py -v -s
        env:
          SEED: "invite couch cloud pave stuff cabbage usual rigid dragon warm cable price fame warfare next swallow worth opera suggest flame patch undo position arctic"
